<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.5 on win32)" generated="20201122 20:14:26.476" rpa="false">
<suite id="s1" name="TestCases" source="C:\Users\Punith.Keshav\PycharmProjects\RobotFrameworkProject\TestCases">
<suite id="s1-s1" name="TC1" source="C:\Users\Punith.Keshav\PycharmProjects\RobotFrameworkProject\TestCases\TC1.robot">
<test id="s1-s1-t1" name="LoginTest">
<kw name="Create Webdriver" library="SeleniumLibrary">
<doc>Creates an instance of Selenium WebDriver.</doc>
<arguments>
<arg>chrome</arg>
<arg>executable_path="path where webdrivers are placed (C://Driverpath//chromedriver.exe)"</arg>
</arguments>
<msg timestamp="20201122 20:14:27.241" level="INFO">Creating an instance of the chrome WebDriver.</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20201122 20:14:27.242" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<status status="PASS" starttime="20201122 20:14:27.241" endtime="20201122 20:14:27.242"></status>
</kw>
<msg timestamp="20201122 20:14:27.293" level="FAIL">TypeError: 'module' object is not callable</msg>
<status status="FAIL" starttime="20201122 20:14:27.240" endtime="20201122 20:14:27.293"></status>
</kw>
<status status="FAIL" starttime="20201122 20:14:27.238" endtime="20201122 20:14:27.294" critical="yes">TypeError: 'module' object is not callable</status>
</test>
<status status="FAIL" starttime="20201122 20:14:26.571" endtime="20201122 20:14:27.296"></status>
</suite>
<status status="FAIL" starttime="20201122 20:14:26.485" endtime="20201122 20:14:27.298"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="TestCases">TestCases</stat>
<stat pass="0" fail="1" id="s1-s1" name="TC1">TestCases.TC1</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
